name: "Trivy Vulnerability Scan Action"
description: "A reusable action for scanning repositories with Trivy and uploading results to the GitHub Security tab."
inputs:
  severity:
    description: "The severity levels to scan for (e.g., CRITICAL,HIGH)"
    required: true
    default: "CRITICAL,HIGH"
  ignore-unfixed:
    description: "Whether to ignore unfixed vulnerabilities"
    required: false
    default: "true"
  scan-type:
    description: "The scan type (e.g., 'fs' for repository scan)"
    required: true
    default: "fs"
  format:
    description: "The format of the scan output"
    required: true
    default: "sarif"
  output:
    description: "The output file for the scan results"
    required: true
    default: "trivy-results.sarif"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # 0.24.0
      with:
        scan-type: ${{ inputs.scan-type }}
        ignore-unfixed: ${{ inputs.ignore-unfixed }}
        format: ${{ inputs.format }}
        output: ${{ inputs.output }}
        severity: ${{ inputs.severity }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@294a9d92911152fe08befb9ec03e240add280cb3 # v3
      with:
        sarif_file: ${{ inputs.output }}
