---
name: Manage GitHub Teams and Members

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

permissions: read-all

jobs:
  manage-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Create App token
        id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FSDH_TEAM_ADMIN_APP_ID }}
          private-key: ${{ secrets.FSDH_TEAM_ADMIN_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up GitHub CLI
        run: gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

      - name: Manage Teams
        run: |
          # Function to extract team properties from JSON
          get_team_properties() {
            local team_json=$1
            TEAM_NAME=$(echo "$team_json" | jq -r '.name')
            TEAM_SLUG=$(echo "$TEAM_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
            TEAM_DESCRIPTION=$(echo "$team_json" | jq -r '.description // ""')
            TEAM_PRIVACY=$(echo "$team_json" | jq -r '.privacy // "closed"')
            TEAM_PERMISSION=$(echo "$team_json" | jq -r '.permission // "push"')
            TEAM_NOTIFICATION=$(echo "$team_json" | jq -r '.notification_setting // "notifications_enabled"')
          }

          # Create an array for team files
          IFS=$'\n' read -rd '' -a team_files <<< "$(find ./.github/workflows/team-configs -name '*.json')"

          if [[ ${#team_files[@]} -eq 0 ]]; then
            echo "No team configuration files found. Exiting..."
            exit 1
          fi

          # Create an array for existing teams
          IFS=$'\n' read -rd '' -a existing_teams <<< "$(gh api orgs/${{ github.repository_owner }}/teams --jq '.[].slug')"

          # Loop over each team file
          for team_file in "${team_files[@]}"; do
            echo "Processing team configuration from $team_file..."
            team=$(cat "$team_file")
            get_team_properties "$team"

            team_exists=false
            for existing_team in "${existing_teams[@]}"; do
              if [[ "$existing_team" == "$TEAM_SLUG" ]]; then
                team_exists=true
                break
              fi
            done

            if [[ "$team_exists" == true ]]; then
              echo "Updating team $TEAM_NAME..."
              gh api \
                --method PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams/${TEAM_SLUG}" \
                -f "name=${TEAM_NAME}" \
                -f "description=${TEAM_DESCRIPTION}" \
                -f "privacy=${TEAM_PRIVACY}" \
                -f "notification_setting=${TEAM_NOTIFICATION}"
            else
              echo "Creating team $TEAM_NAME..."
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams" \
                -f "name=${TEAM_NAME}" \
                -f "description=${TEAM_DESCRIPTION}" \
                -f "privacy=${TEAM_PRIVACY}" \
                -f "permission=${TEAM_PERMISSION}" \
                -f "notification_setting=${TEAM_NOTIFICATION}"
            fi
          done

          # Deleting teams that do not have a corresponding JSON file
          for team_slug in "${existing_teams[@]}"; do
            json_file=$(find ./.github/workflows/team-configs -name "${team_slug}.json")

            if [[ -z "$json_file" ]]; then
              echo "No JSON file found for team $team_slug. Deleting team..."
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams/${team_slug}"
            fi
          done