---
name: Manage GitHub Teams and Members

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

permissions: read-all

jobs:
  manage-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Create App token
        id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FSDH_TEAM_ADMIN_APP_ID }}
          private-key: ${{ secrets.FSDH_TEAM_ADMIN_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up GitHub CLI
        run: gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

      - name: Manage Teams
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
        run: |
          # Create an array for team files
          team_files=($(find ./.github/workflows/team-configs -name '*.json'))

          if [[ ${#team_files[@]} -eq 0 ]]; then
            echo "No team configuration files found. Exiting..."
            exit 1
          fi

          # Create an array for existing teams
          existing_teams=($(gh api orgs/${{ github.repository_owner }}/teams --jq '.[].slug'))

          # Loop over each team file
          for team_file in "${team_files[@]}"; do
            echo "Processing team configuration from $team_file..."
            team=$(cat "$team_file")
            get_team_properties "$team"

            if [[ " ${existing_teams[@]} " =~ " $TEAM_SLUG " ]]; then
              echo "Updating team $TEAM_NAME..."
              gh api \
                --method PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams/${TEAM_SLUG}" \
                -f "name=${TEAM_NAME}" \
                -f "description=${TEAM_DESCRIPTION}" \
                -f "privacy=${TEAM_PRIVACY}" \
                -f "notification_setting=${TEAM_NOTIFICATION}"
            else
              echo "Creating team $TEAM_NAME..."
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams" \
                -f "name=${TEAM_NAME}" \
                -f "description=${TEAM_DESCRIPTION}" \
                -f "privacy=${TEAM_PRIVACY}" \
                -f "permission=${TEAM_PERMISSION}" \
                -f "notification_setting=${TEAM_NOTIFICATION}"
            fi
          done

          # Deleting teams that do not have a corresponding JSON file
          for team_slug in "${existing_teams[@]}"; do
            json_file=$(find ./.github/workflows/team-configs -name "${team_slug}.json")

            if [[ -z "$json_file" ]]; then
              echo "No JSON file found for team $team_slug. Deleting team..."
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/${{ github.repository_owner }}/teams/${team_slug}"
            fi
          done

